; Listing generated by Microsoft (R) Optimizing Compiler Version 19.16.27031.1 

	TITLE	D:\CPPBASIC\DAY3\함수호출규약.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	?f1@@YAXHH@Z					; f1
PUBLIC	?f2@@YAXHH@Z					; f2
PUBLIC	?f3@@YGXHH@Z					; f3
PUBLIC	?f4@@YIXHH@Z					; f4
PUBLIC	_main
; Function compile flags: /Odtp
; File d:\cppbasic\day3\함수호출규약.cpp
_TEXT	SEGMENT
_main	PROC

; 40   : {

	push	ebp
	mov	ebp, esp

; 41   : 	f1(1, 2);

	push	2
	push	1
	call	?f1@@YAXHH@Z				; f1
	add	esp, 8

; 42   : 	f2(1, 2);

	push	2
	push	1
	call	?f2@@YAXHH@Z				; f2
	add	esp, 8

; 43   : 	f3(1, 2);

	push	2
	push	1
	call	?f3@@YGXHH@Z				; f3

; 44   : 	f4(1, 2);

	mov	edx, 2
	mov	ecx, 1
	call	?f4@@YIXHH@Z				; f4

; 45   : }

	xor	eax, eax
	pop	ebp
	ret	0
_main	ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
; File d:\cppbasic\day3\함수호출규약.cpp
_TEXT	SEGMENT
_a$ = -8						; size = 4
_b$ = -4						; size = 4
?f4@@YIXHH@Z PROC					; f4
; _a$ = ecx
; _b$ = edx

; 37   : void __fastcall f4(int a, int b) { }

	push	ebp
	mov	ebp, esp
	sub	esp, 8
	mov	DWORD PTR _b$[ebp], edx
	mov	DWORD PTR _a$[ebp], ecx
	mov	esp, ebp
	pop	ebp
	ret	0
?f4@@YIXHH@Z ENDP					; f4
_TEXT	ENDS
; Function compile flags: /Odtp
; File d:\cppbasic\day3\함수호출규약.cpp
_TEXT	SEGMENT
_a$ = 8							; size = 4
_b$ = 12						; size = 4
?f3@@YGXHH@Z PROC					; f3

; 36   : void __stdcall  f3(int a, int b) { }

	push	ebp
	mov	ebp, esp
	pop	ebp
	ret	8
?f3@@YGXHH@Z ENDP					; f3
_TEXT	ENDS
; Function compile flags: /Odtp
; File d:\cppbasic\day3\함수호출규약.cpp
_TEXT	SEGMENT
_a$ = 8							; size = 4
_b$ = 12						; size = 4
?f2@@YAXHH@Z PROC					; f2

; 35   : void __cdecl    f2(int a, int b) { }

	push	ebp
	mov	ebp, esp
	pop	ebp
	ret	0
?f2@@YAXHH@Z ENDP					; f2
_TEXT	ENDS
; Function compile flags: /Odtp
; File d:\cppbasic\day3\함수호출규약.cpp
_TEXT	SEGMENT
_a$ = 8							; size = 4
_b$ = 12						; size = 4
?f1@@YAXHH@Z PROC					; f1

; 34   : void            f1(int a, int b) { }

	push	ebp
	mov	ebp, esp
	pop	ebp
	ret	0
?f1@@YAXHH@Z ENDP					; f1
_TEXT	ENDS
END
